# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('nickname', models.CharField(max_length=20)),
                ('head', models.URLField()),
                ('password', models.CharField(max_length=20)),
                ('article_id', models.TextField()),
            ],
        ),
    ]
