# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='article_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
