# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20171101_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IMG',
        ),
    ]
