# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20171102_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likeo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
