# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_article_likeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='noname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
