# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_article_noname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='subcomment',
            old_name='commnet',
            new_name='commnet_id',
        ),
    ]
