# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20171102_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcomment',
            name='time',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
