# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20171104_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='articlelike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('article_id', models.CharField(max_length=20)),
            ],
        ),
    ]
