# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_articlelike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likeo',
        ),
    ]
