# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_articlelike_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelike',
            name='user2_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
