# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_articlelike_user2_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
