# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20171106_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('img_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
    ]
