# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20171107_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.ImageField(upload_to='img'),
        ),
    ]
